name: Build Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KASIRALVA_KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore
          echo "${{ secrets.KASIRALVA_KEYSTORE_BASE64 }}" | base64 --decode > app/kasiralva-release.keystore

      - name: Build Android Release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
          # Alias/Variabel umum lainnya
          STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
          RELEASE_STORE_FILE: release.keystore
          KEYSTORE_FILE: release.keystore
        run: |
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: KasirAlva-Release-APK
          path: app/build/outputs/apk/release/*.apk
